# Checkov Configuration for Wiz Exercise
# This project intentionally contains security vulnerabilities for demonstration purposes.
# 意図的な脆弱性を含むため、特定のチェックをスキップします。

skip-check:
  # AKS Related - 意図的な脆弱性
  - CKV_AZURE_141  # AKS local admin account disabled
  - CKV_AZURE_7    # AKS Network Policy configured
  - CKV_AZURE_226  # Ephemeral OS disks
  - CKV_AZURE_227  # AKS encrypt temp disks

  # Storage Account Related - 意図的な脆弱性
  - CKV_AZURE_34   # Blob container public access (教育目的で有効化)
  - CKV_AZURE_35   # Storage default network access deny
  - CKV_AZURE_3    # HTTPS traffic only
  - CKV_AZURE_206  # Storage replication
  - CKV_AZURE_44   # TLS version
  - CKV_AZURE_43   # Storage naming rules

# Verbose output for educational purposes
output: cli

# Continue on error for demonstration
soft-fail: true

# Framework specific settings
framework:
  - bicep
  - arm

# Exclude paths
skip-path:
  - infra/main.json
  - infra/modules/vm-mongodb.json
